#!/usr/bin/env bash
# Open Grid local installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/<org>/opengrid/main/scripts/install.sh | bash
#   # or, from a clone:
#   ./scripts/install.sh
#
# What it does:
#   1. Checks prerequisites (git, node>=20, pnpm)
#   2. Clones the repo into ./opengrid (skipped if already inside a clone)
#   3. Generates a SESSION_SECRET if one isn't already in .env
#   4. Installs deps with pnpm
#   5. Prints the two commands to start the API + web canvas
#
# It deliberately does NOT start the servers — your shell, your rules.

set -euo pipefail

REPO_URL="${OPENGRID_REPO:-https://github.com/fleet-watcher/opengrid.git}"
TARGET_DIR="${OPENGRID_DIR:-opengrid}"

bold()  { printf "\033[1m%s\033[0m\n" "$*"; }
ok()    { printf "  \033[32m✓\033[0m %s\n" "$*"; }
warn()  { printf "  \033[33m!\033[0m %s\n" "$*"; }
fail()  { printf "  \033[31m✗\033[0m %s\n" "$*" >&2; exit 1; }

bold "Open Grid · local install"
echo

# ── 1. prereqs ────────────────────────────────────────────────────────────────
command -v git  >/dev/null || fail "git is required"
command -v node >/dev/null || fail "node >= 20 is required (https://nodejs.org)"

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || fail "node >= 20 required (you have $(node -v))"
ok "node $(node -v)"

if ! command -v pnpm >/dev/null; then
  warn "pnpm not found — installing via corepack"
  corepack enable >/dev/null 2>&1 || fail "corepack failed; install pnpm manually: https://pnpm.io/installation"
  corepack prepare pnpm@latest --activate >/dev/null
fi
ok "pnpm $(pnpm -v)"

# ── 2. clone (or stay in current dir if already a clone) ──────────────────────
if [ -f "pnpm-workspace.yaml" ] && [ -d "artifacts/api-server" ]; then
  ok "already inside an Open Grid checkout — skipping clone"
else
  if [ -d "$TARGET_DIR" ]; then
    warn "$TARGET_DIR already exists — pulling latest"
    git -C "$TARGET_DIR" pull --ff-only
  else
    bold "Cloning into ./$TARGET_DIR"
    git clone --depth 1 "$REPO_URL" "$TARGET_DIR"
  fi
  cd "$TARGET_DIR"
fi

# ── 3. SESSION_SECRET ─────────────────────────────────────────────────────────
ENV_FILE=".env.local"
if [ -f "$ENV_FILE" ] && grep -q '^SESSION_SECRET=' "$ENV_FILE"; then
  ok "$ENV_FILE already has SESSION_SECRET — keeping it"
else
  if command -v openssl >/dev/null; then
    SECRET="$(openssl rand -hex 32)"
  else
    SECRET="$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')"
  fi
  {
    echo "# Generated by scripts/install.sh — do not commit"
    echo "SESSION_SECRET=$SECRET"
    echo "# Required in production. Comma-separated. Add your real hostnames here."
    echo "# ALLOWED_ORIGINS=http://localhost:5173"
    echo "# Optional. Defaults to ~/.opengrid-workspaces"
    echo "# WORKSPACES_ROOT=$HOME/.opengrid-workspaces"
  } > "$ENV_FILE"
  ok "wrote $ENV_FILE with a fresh SESSION_SECRET"
fi

# ── 4. install ────────────────────────────────────────────────────────────────
bold "Installing dependencies (this may take a minute)"
pnpm install

# ── 5. next steps ─────────────────────────────────────────────────────────────
echo
bold "Done. To run Open Grid locally:"
cat <<EOF

  # Terminal 1 — API + WebSocket server
  PORT=4000 \\
  \$(grep -v '^#' .env.local | xargs) \\
  pnpm --filter @workspace/api-server run dev

  # Terminal 2 — web canvas
  PORT=5173 \\
  pnpm --filter @workspace/opengrid-canvas run dev

  # Then open  http://localhost:5173

Make sure the agent CLIs you want are on \$PATH:
  claude · codex · gemini · cursor-agent · grok · aider
Check availability inside the app or via:  curl localhost:4000/api/cli-status

EOF
